version: '2'

services:
  dictionaryManagerDb:
    container_name: dictionary-manager-mongo
    image: bitnami/mongodb:4.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: dictionary-manager
      MONGODB_ROOT_PASSWORD: password123
volumes:
  mongodb_data:
    name: dictionary-manager-mongo-data
    driver: local
